### ISSUE TITLE
Bootstrapping playbooks failed on TASK [galera_client : Drop local .my.cnf file]

### ISSUE THREAD

**Issue by jackiehjm** [Wind-River/meta-akraino#51]
## Error: fatal: [controller-1]: FAILED! => {"failed": true, "msg": "'galera_root_password' is undefined"}

logs in cm.log:
```
PLAY [Install galera server] ***************************************************

TASK [galera_client : Gather variables for each operating system] **************
Friday 14 February 2020  05:11:15 -0500 (0:00:00.126)       0:00:41.752 *******
ok: [controller-1] => (item=/etc/ansible/roles/galera_client/vars/redhat-7.yml)

TASK [galera_client : Drop local .my.cnf file] *********************************
Friday 14 February 2020  05:11:15 -0500 (0:00:00.044)       0:00:41.796 *******
fatal: [controller-1]: FAILED! => {"failed": true, "msg": "'galera_root_password' is undefined"}

PLAY RECAP *********************************************************************
controller-1               : ok=76   changed=35   unreachable=0    failed=1

Friday 14 February 2020  05:11:15 -0500 (0:00:00.052)       0:00:41.849 *******
===============================================================================
partfs_rootdisk : Running a script to remount volume on target dir ----- 12.54s
partfs_rootdisk : Creating LVM ------------------------------------------ 4.98s
partfs_rootdisk : Stop all cloud-init services and disable them --------- 4.59s
Report installation progress -------------------------------------------- 3.59s
partfs_rootdisk : delete temporary partition ---------------------------- 1.39s
Set Timezone ------------------------------------------------------------ 1.33s
Set Timezone ------------------------------------------------------------ 1.17s
partfs_rootdisk : Create fstab entry. ----------------------------------- 1.04s
partfs_rootdisk : Create XFS filesystem on LVM -------------------------- 1.04s
partfs_rootdisk : Create /tmp/<node_name>localstorage.json file --------- 0.54s
ntp : Copy the ntp.conf template file ----------------------------------- 0.49s
partfs_rootdisk : Create PV VG ------------------------------------------ 0.46s
initial_poweroff_hosts : Ensure all the nodes in the deployment are powered-off. --- 0.34s
partfs_rootdisk : remove physical volume (if any) ----------------------- 0.30s
Report installation progress -------------------------------------------- 0.29s
partfs_rootdisk : Create Partition for LVMs ----------------------------- 0.28s
Report installation progress -------------------------------------------- 0.28s
partfs_rootdisk : remove physical volume (if any) ----------------------- 0.28s
Report installation progress -------------------------------------------- 0.28s
ntp : enable ntpdate at boot time --------------------------------------- 0.26s
[2020-02-14 05:11:15,784   ERROR cmactivateserverhandler(100)] Skipping installationactivator, got exception Playbook bootstrapping-playbook.yml failed
```

**Comment by jackiehjm** [comment]
In build 185:
```
[newadmin@controller-1 openstack_deploy]$ sudo grep -r galera_root_password *
user_secrets.yml:galera_root_password: Z-baf01d5296ed28389cd215e81fe8e8

[newadmin@controller-1 openstack_deploy]$ sudo wc -l user_secrets.yml
89 user_secrets.yml
```

But in wrl:
```
root@controller-1:/etc/openstack_deploy# grep -r galera_root_password *
root@controller-1:/etc/openstack_deploy# wc -l user_secrets.yml
6 user_secrets.yml
```

We are missing many items in user_secrets.yml

**Comment by gaolitao** [comment]
000-user_secrets.yml and restful.yaml are missing under directory of /etc/required-secrets

- restful.yaml is supposed to be installed from pkg python-yarf (but not in the place in rootfs)
- 000-user_secrets.yml  ( is supposed to be copied from /opt/openstack-ansible/etc/openstack_deploy/user_secrets.yml during pkg_postinst_ontarget of openstack-ansible-17.0.2+git0+2bdc44499b-r0.corei7_64)

user_secrets related ansbile tasks:
```
bootstrap_host_aio_config_path:  /opt/openstack-ansible/etc/openstack_deploy/
bootstrap_host_aio_script_path:  /opt/openstack-ansible/scripts/

- name: Assemble final user_secrets.yml
  assemble:
    src: /etc/required-secrets
    dest: /opt/openstack-ansible/etc/openstack_deploy/user_secrets.yml
    delimiter: '\n'
    owner: root
    group: root
    mode: 0644
    ignore_hidden: true

- name: Deploy user_secrets file
  config_template:
    src: "{{ bootstrap_host_aio_config_path }}/user_secrets.yml"
    dest: "/etc/openstack_deploy/{{ bootstrap_host_user_secrets_filename }}"
    config_overrides: "{{ user_secrets_overrides | default({}) }}"
    config_type: "yaml"
  tags:
    - deploy-user-secrets

- name: Generate any missing values in user_secrets
  command: "{{ bootstrap_host_aio_script_path }}/pw-token-gen.py --file /etc/openstack_deploy/{{ bootstrap_host_user_secrets_filename }}"
  changed_when: false
  tags:
    - generate_secrets
```
